# Generated by Django 5.1.1 on 2024-10-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_blogs', '0002_blog_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
