# Generated by Django 5.1.1 on 2024-10-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_blogs', '0003_tag_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feature_approve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='feature_request',
            field=models.BooleanField(default=False),
        ),
    ]
