# Generated by Django 5.1.1 on 2024-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_blogs', '0004_blog_feature_approve_blog_feature_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feature_approve',
            field=models.BooleanField(default=False),
        ),
    ]
