# Generated by Django 5.1.1 on 2024-10-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_blogs', '0006_remove_blog_feature_approve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature_request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
