# Generated by Django 5.1.1 on 2024-10-12 02:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_blogs', '0007_feature_request_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature_Request',
            new_name='FeatureRequest',
        ),
    ]
