# Generated by Django 5.1.1 on 2024-10-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_blogs', '0008_rename_feature_request_featurerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feature_request',
            field=models.BooleanField(default=False),
        ),
    ]
