# Generated by Django 5.1.1 on 2024-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_blogs', '0009_blog_feature_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
